name: Post to mozilla.social
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send toot to Mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
          url: ${{ secrets.MASTODON_URL }} # https://example.social
          message: "We just posted our weekly meeting notes. Check them out: https://mozilla-necko.github.io/meeting-notes/"
          
